"""
WorkmAIn CLI
Google Drive Command Group
gdocs.py v1.1
20260309

CLI commands for archiving daily work artifacts to Google Drive.

Commands:
- gdocs auth [--reauth]          # Authenticate / re-authenticate
- gdocs status                   # Auth state, cached folders, recent uploads
- gdocs upload-notes             # DB notes → markdown → staging/notes/ → Drive
- gdocs upload-report            # staging/reports/daily_internal_YYYY-MM-DD.md → Drive
- gdocs upload-clockify          # staging/clockify/Clockify_YYYYMMDD.pdf → Drive
- gdocs upload-all               # Runs all three in sequence

Drive structure:
    {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Raw_Notes/
    {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Reports/
    {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Clockify/

Version History:
- v1.0: Initial implementation (Phase 7 Gate 3)
- v1.1: Fix Rich MarkupError in gdocs auth — [dim] tag split across two print() calls
"""

import os
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Optional

import click
from rich.console import Console
from rich.panel import Panel
from rich.rule import Rule

from workmain.database.connection import get_db
from workmain.database.repositories.notes_repo import NotesRepository
from workmain.database.repositories.gdrive_repository import GDriveRepository
from workmain.integrations.gdrive.auth import (
    is_authenticated,
    get_service,
    GDriveAuthError,
)
from workmain.integrations.gdrive.client import GDriveClient, GDriveClientError
from workmain.integrations.gdrive import cache as folder_cache


console = Console()

# Project root: workmain/cli/commands/gdocs.py → 4 parents up
_PROJECT_ROOT  = Path(__file__).parent.parent.parent.parent
_STAGING_NOTES = _PROJECT_ROOT / "staging" / "notes"
_STAGING_REPORTS = _PROJECT_ROOT / "staging" / "reports"
_STAGING_CLOCKIFY = _PROJECT_ROOT / "staging" / "clockify"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_date_arg(date_str: Optional[str]) -> date:
    """Parse YYYYMMDD string to date, defaulting to today."""
    if date_str is None:
        return date.today()
    try:
        return datetime.strptime(date_str, "%Y%m%d").date()
    except ValueError:
        raise click.BadParameter(
            f"Invalid date '{date_str}'. Expected format: YYYYMMDD (e.g. 20260309)."
        )


def _require_env_root() -> str:
    """Return GDRIVE_TIMECARDS_ROOT or abort with a clear message."""
    root = os.environ.get("GDRIVE_TIMECARDS_ROOT", "").strip()
    if not root:
        console.print(
            "\n[red]✗ GDRIVE_TIMECARDS_ROOT is not set.[/red] "
            "Add it to your .env file.\n"
        )
        sys.exit(1)
    return root


def _require_auth() -> None:
    """Abort with a clear message if not authenticated."""
    if not is_authenticated():
        console.print(
            "\n[red]✗ Not authenticated.[/red] "
            "Run: [bold]workmain gdocs auth[/bold]\n"
        )
        sys.exit(1)


def _get_client() -> GDriveClient:
    """Build an authenticated GDriveClient, handling auth errors."""
    try:
        svc = get_service()
        return GDriveClient(svc)
    except GDriveAuthError as exc:
        console.print(f"\n[red]✗ Auth error:[/red] {exc}\n")
        sys.exit(1)


def _format_notes_markdown(notes: list, target_date: date) -> str:
    """
    Format a list of Note objects as the canonical §3.8 markdown.

    Format:
        # Daily Notes — YYYY-MM-DD

        ## [tag] HH:MM
        Note content here.

        ---
        *Generated by WorkmAIn on YYYY-MM-DD HH:MM*

    Rules:
    - Notes ordered by created_at ascending (already sorted by repo)
    - Tags shown as full display names in brackets
    - Multiple tags: [tag1] [tag2] HH:MM
    - Time in 24-hour format (HH:MM)
    - Empty body: included with empty line
    """
    date_str = target_date.strftime("%Y-%m-%d")
    lines = [f"# Daily Notes — {date_str}", ""]

    for note in notes:
        tags = note.tags or []
        tag_str = " ".join(f"[{t}]" for t in tags) if tags else "[internal-only]"
        time_str = note.created_at.strftime("%H:%M") if note.created_at else "00:00"
        lines.append(f"## {tag_str} {time_str}")
        lines.append(note.content if note.content else "")
        lines.append("")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines.append("---")
    lines.append(f"*Generated by WorkmAIn on {now}*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Command group
# ---------------------------------------------------------------------------

@click.group()
def gdocs():
    """
    Google Drive integration commands.

    Archive daily work artifacts (notes, reports, Clockify PDFs) to a
    structured Google Drive folder hierarchy.

    \b
    Drive structure:
      {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Raw_Notes/
      {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Reports/
      {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Clockify/
    """
    pass


# ---------------------------------------------------------------------------
# gdocs auth
# ---------------------------------------------------------------------------

@gdocs.command("auth")
@click.option("--reauth", is_flag=True, default=False,
              help="Force re-authentication even if a valid token exists.")
def gdocs_auth(reauth: bool):
    """
    Authenticate with Google Drive.

    Uses a WSL-safe console flow (copy-paste URL + auth code — no browser spawn).
    Reuses an existing token if valid unless --reauth is passed.
    After auth, verifies the current month's folder structure in Drive.

    \b
    Examples:
      workmain gdocs auth
      workmain gdocs auth --reauth
    """
    _require_env_root()

    if not reauth and is_authenticated():
        console.print(
            "\n[green]✓ Already authenticated.[/green] "
            "Use [bold]--reauth[/bold] to refresh.\n"
        )
        return

    console.print("\n[cyan]Starting Google Drive authentication...[/cyan]")
    console.print("[dim]A URL will be printed. Open it in your browser, sign in,\nthen paste the authorization code below.[/dim]\n")

    try:
        svc = get_service()
        client = GDriveClient(svc)
    except GDriveAuthError as exc:
        console.print(f"\n[red]✗ Authentication failed:[/red] {exc}\n")
        sys.exit(1)

    # Cache folder structure for current month
    period = date.today().strftime("%Y%m")
    try:
        ids = client.ensure_period_structure(period)
        console.print("\n[green]✓ Authentication complete. Drive folder structure verified.[/green]")
        console.print(f"  [dim]Period: {period}[/dim]")
        for key, fid in ids.items():
            console.print(f"  [dim]{key:<12} → {fid}[/dim]")
        console.print()
    except GDriveClientError as exc:
        console.print(f"\n[red]✗ Drive API error:[/red] {exc}\n")
        sys.exit(1)


# ---------------------------------------------------------------------------
# gdocs status
# ---------------------------------------------------------------------------

@gdocs.command("status")
def gdocs_status():
    """
    Show Google Drive integration status.

    Displays authentication state, cached folder IDs, and recent upload history.

    \b
    Example:
      workmain gdocs status
    """
    root_name = os.environ.get("GDRIVE_TIMECARDS_ROOT", "(not set)")
    authed = is_authenticated()

    console.print()
    console.print(Panel.fit(
        "Google Drive Integration",
        border_style="cyan"
    ))
    console.print(Rule(style="dim"))

    auth_icon = "[green]✓ Authenticated[/green]" if authed else "[red]✗ Not authenticated[/red]"
    console.print(f"Auth          {auth_icon}")

    if not authed:
        console.print("\nRun: [bold]workmain gdocs auth[/bold]\n")
        return

    from workmain.integrations.gdrive.auth import TOKEN_PATH
    console.print(f"Token path    [dim]{TOKEN_PATH}[/dim]")
    console.print(f"Root folder   [dim]{root_name} (GDRIVE_TIMECARDS_ROOT)[/dim]")

    # Cached folders
    cache = folder_cache.load_cache()
    if cache:
        console.print()
        console.print("[bold]Cached Folders[/bold]")
        for period, entries in sorted(cache.items()):
            for sub, fid in entries.items():
                label = "root" if sub == "root" else sub
                console.print(f"  {period}  {label:<12} → {fid}")

    # Recent uploads
    db = get_db()
    session = db.get_session()
    try:
        repo = GDriveRepository(session)
        recent = repo.get_recent_uploads(limit=5)
        console.print()
        console.print("[bold]Recent Uploads (last 5)[/bold]")
        if recent:
            for rec in recent:
                console.print(
                    f"  {rec.upload_date}  {rec.upload_type:<10} {rec.filename}"
                )
        else:
            console.print("  [dim](none yet)[/dim]")
    finally:
        session.close()

    console.print()


# ---------------------------------------------------------------------------
# gdocs upload-notes
# ---------------------------------------------------------------------------

@gdocs.command("upload-notes")
@click.option("--date", "date_str", type=str, default=None,
              help="Target date YYYYMMDD. Default: today.")
@click.option("--dry-run", is_flag=True, default=False,
              help="Show what would be uploaded — no Drive writes.")
@click.option("--force", is_flag=True, default=False,
              help="Re-upload even if already uploaded for this date.")
def gdocs_upload_notes(date_str: Optional[str], dry_run: bool, force: bool):
    """
    Export today's notes to markdown and upload to Drive.

    Queries the database for all notes on the target date, formats them
    as a markdown file, writes to staging/notes/, then uploads to
    {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Raw_Notes/.

    \b
    Examples:
      workmain gdocs upload-notes
      workmain gdocs upload-notes --date 20260308
      workmain gdocs upload-notes --dry-run
      workmain gdocs upload-notes --force
    """
    _require_env_root()
    _require_auth()

    target_date = _parse_date_arg(date_str)
    period      = target_date.strftime("%Y%m")
    filename    = f"Daily_Notes_{target_date.strftime('%Y%m%d')}.md"
    local_path  = _STAGING_NOTES / filename

    db = get_db()
    session = db.get_session()
    try:
        gdrive_repo = GDriveRepository(session)

        # Duplicate protection
        if not force and gdrive_repo.already_uploaded(filename, target_date, "notes"):
            console.print(
                f"\n[yellow]⚠ Notes for {target_date} already uploaded.[/yellow] "
                "Use [bold]--force[/bold] to overwrite.\n"
            )
            return

        # Fetch notes from DB
        notes_repo = NotesRepository(session)
        notes = notes_repo.get_by_date(target_date)

        root_name = os.environ.get("GDRIVE_TIMECARDS_ROOT", "Timecards")

        if dry_run:
            console.print(f"\n[dim][DRY RUN] Notes for {target_date}: {len(notes)} note(s)[/dim]")
            console.print(f"[dim][DRY RUN] Would write: {local_path}[/dim]")
            console.print(
                f"[dim][DRY RUN] Would upload: {filename} "
                f"→ {root_name}/{period}/Raw_Notes/[/dim]\n"
            )
            return

        # Format markdown
        content = _format_notes_markdown(notes, target_date)

        # Write to staging
        _STAGING_NOTES.mkdir(parents=True, exist_ok=True)
        local_path.write_text(content, encoding="utf-8")

        # Upload
        client = _get_client()
        folder_ids = client.ensure_period_structure(period)
        drive_file_id = client.upload_file(
            local_path=local_path,
            folder_id=folder_ids["Raw_Notes"],
            filename=filename,
            mime_type="text/markdown",
        )

        # Record in DB
        gdrive_repo.record_upload(
            local_path=str(local_path),
            drive_file_id=drive_file_id,
            drive_folder_id=folder_ids["Raw_Notes"],
            filename=filename,
            upload_type="notes",
            upload_date=target_date,
        )

        console.print(
            f"\n[green]✓ Uploaded:[/green] {filename} "
            f"→ {root_name}/{period}/Raw_Notes/\n"
        )

    except GDriveClientError as exc:
        console.print(f"\n[red]✗ Drive API error:[/red] {exc}. Check your connection and retry.\n")
        sys.exit(1)
    finally:
        session.close()


# ---------------------------------------------------------------------------
# gdocs upload-report
# ---------------------------------------------------------------------------

@gdocs.command("upload-report")
@click.option("--date", "date_str", type=str, default=None,
              help="Target date YYYYMMDD. Default: today.")
@click.option("--dry-run", is_flag=True, default=False,
              help="Show what would be uploaded — no Drive writes.")
@click.option("--force", is_flag=True, default=False,
              help="Re-upload even if already uploaded for this date.")
def gdocs_upload_report(date_str: Optional[str], dry_run: bool, force: bool):
    """
    Upload the daily internal report from staging to Drive.

    Looks for staging/reports/daily_internal_YYYY-MM-DD.md and uploads
    to {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Reports/.

    \b
    Examples:
      workmain gdocs upload-report
      workmain gdocs upload-report --date 20260308
      workmain gdocs upload-report --dry-run
      workmain gdocs upload-report --force
    """
    _require_env_root()
    _require_auth()

    target_date   = _parse_date_arg(date_str)
    period        = target_date.strftime("%Y%m")
    # Report files use YYYY-MM-DD hyphenated format (matches report_generator.py output)
    report_name   = f"daily_internal_{target_date.strftime('%Y-%m-%d')}.md"
    local_path    = _STAGING_REPORTS / report_name
    # Drive destination filename keeps the same name
    filename      = report_name
    root_name     = os.environ.get("GDRIVE_TIMECARDS_ROOT", "Timecards")

    if dry_run:
        exists_note = "found" if local_path.exists() else "NOT FOUND — run: workmain report save daily_internal"
        console.print(f"\n[dim][DRY RUN] Report: {report_name} ({exists_note})[/dim]")
        console.print(
            f"[dim][DRY RUN] Would upload: {filename} "
            f"→ {root_name}/{period}/Reports/[/dim]\n"
        )
        return

    if not local_path.exists():
        console.print(
            f"\n[red]✗ No report found for {target_date}.[/red]\n"
            f"  Run: [bold]workmain report save daily_internal[/bold]\n"
        )
        sys.exit(1)

    db = get_db()
    session = db.get_session()
    try:
        gdrive_repo = GDriveRepository(session)

        if not force and gdrive_repo.already_uploaded(filename, target_date, "report"):
            console.print(
                f"\n[yellow]⚠ Report for {target_date} already uploaded.[/yellow] "
                "Use [bold]--force[/bold] to overwrite.\n"
            )
            return

        client = _get_client()
        folder_ids = client.ensure_period_structure(period)
        drive_file_id = client.upload_file(
            local_path=local_path,
            folder_id=folder_ids["Reports"],
            filename=filename,
            mime_type="text/markdown",
        )

        gdrive_repo.record_upload(
            local_path=str(local_path),
            drive_file_id=drive_file_id,
            drive_folder_id=folder_ids["Reports"],
            filename=filename,
            upload_type="report",
            upload_date=target_date,
        )

        console.print(
            f"\n[green]✓ Uploaded:[/green] {filename} "
            f"→ {root_name}/{period}/Reports/\n"
        )

    except GDriveClientError as exc:
        console.print(f"\n[red]✗ Drive API error:[/red] {exc}. Check your connection and retry.\n")
        sys.exit(1)
    finally:
        session.close()


# ---------------------------------------------------------------------------
# gdocs upload-clockify
# ---------------------------------------------------------------------------

@gdocs.command("upload-clockify")
@click.option("--date", "date_str", type=str, default=None,
              help="Target date YYYYMMDD. Default: today.")
@click.option("--dry-run", is_flag=True, default=False,
              help="Show what would be uploaded — no Drive writes.")
@click.option("--force", is_flag=True, default=False,
              help="Re-upload even if already uploaded for this date.")
def gdocs_upload_clockify(date_str: Optional[str], dry_run: bool, force: bool):
    """
    Upload the Clockify PDF from staging to Drive.

    Looks for staging/clockify/Clockify_YYYYMMDD.pdf and uploads
    to {GDRIVE_TIMECARDS_ROOT}/YYYYMM/Clockify/.

    \b
    Examples:
      workmain gdocs upload-clockify
      workmain gdocs upload-clockify --date 20260308
      workmain gdocs upload-clockify --dry-run
      workmain gdocs upload-clockify --force
    """
    _require_env_root()
    _require_auth()

    target_date = _parse_date_arg(date_str)
    period      = target_date.strftime("%Y%m")
    filename    = f"Clockify_{target_date.strftime('%Y%m%d')}.pdf"
    local_path  = _STAGING_CLOCKIFY / filename
    root_name   = os.environ.get("GDRIVE_TIMECARDS_ROOT", "Timecards")

    if dry_run:
        exists_note = "found" if local_path.exists() else "NOT FOUND — run: workmain clockify report save daily"
        console.print(f"\n[dim][DRY RUN] Clockify PDF: {filename} ({exists_note})[/dim]")
        console.print(
            f"[dim][DRY RUN] Would upload: {filename} "
            f"→ {root_name}/{period}/Clockify/[/dim]\n"
        )
        return

    if not local_path.exists():
        console.print(
            f"\n[red]✗ No Clockify PDF found for {target_date}.[/red]\n"
            f"  Run: [bold]workmain clockify report save daily[/bold]\n"
        )
        sys.exit(1)

    db = get_db()
    session = db.get_session()
    try:
        gdrive_repo = GDriveRepository(session)

        if not force and gdrive_repo.already_uploaded(filename, target_date, "clockify"):
            console.print(
                f"\n[yellow]⚠ Clockify PDF for {target_date} already uploaded.[/yellow] "
                "Use [bold]--force[/bold] to overwrite.\n"
            )
            return

        client = _get_client()
        folder_ids = client.ensure_period_structure(period)
        drive_file_id = client.upload_file(
            local_path=local_path,
            folder_id=folder_ids["Clockify"],
            filename=filename,
            mime_type="application/pdf",
        )

        gdrive_repo.record_upload(
            local_path=str(local_path),
            drive_file_id=drive_file_id,
            drive_folder_id=folder_ids["Clockify"],
            filename=filename,
            upload_type="clockify",
            upload_date=target_date,
        )

        console.print(
            f"\n[green]✓ Uploaded:[/green] {filename} "
            f"→ {root_name}/{period}/Clockify/\n"
        )

    except GDriveClientError as exc:
        console.print(f"\n[red]✗ Drive API error:[/red] {exc}. Check your connection and retry.\n")
        sys.exit(1)
    finally:
        session.close()


# ---------------------------------------------------------------------------
# gdocs upload-all
# ---------------------------------------------------------------------------

@gdocs.command("upload-all")
@click.option("--date", "date_str", type=str, default=None,
              help="Target date YYYYMMDD. Default: today.")
@click.option("--dry-run", is_flag=True, default=False,
              help="Show what would be uploaded — no Drive writes.")
@click.option("--force", is_flag=True, default=False,
              help="Re-upload even if already uploaded for this date.")
@click.pass_context
def gdocs_upload_all(ctx, date_str: Optional[str], dry_run: bool, force: bool):
    """
    Upload notes, report, and Clockify PDF to Drive in sequence.

    Runs upload-notes, upload-report, upload-clockify in order.
    On failure of any step, prompts whether to continue with remaining uploads.

    \b
    Examples:
      workmain gdocs upload-all
      workmain gdocs upload-all --date 20260308
      workmain gdocs upload-all --dry-run
    """
    _require_env_root()
    _require_auth()

    target_date = _parse_date_arg(date_str)
    root_name   = os.environ.get("GDRIVE_TIMECARDS_ROOT", "Timecards")
    period      = target_date.strftime("%Y%m")

    results: dict = {}  # step -> (success, filename or error)

    def _run_step(step_name: str, filename: str, upload_fn) -> bool:
        try:
            upload_fn()
            results[step_name] = (True, filename)
            return True
        except SystemExit:
            results[step_name] = (False, "upload failed")
            return False
        except Exception as exc:
            results[step_name] = (False, str(exc))
            return False

    # --- Notes ---
    notes_filename = f"Daily_Notes_{target_date.strftime('%Y%m%d')}.md"

    def _upload_notes():
        ctx.invoke(
            gdocs_upload_notes,
            date_str=target_date.strftime("%Y%m%d"),
            dry_run=dry_run,
            force=force,
        )

    ok = _run_step("Notes", notes_filename, _upload_notes)
    if not ok:
        ans = click.prompt(
            "Continue with remaining uploads? [Y/n]",
            default="Y",
            show_default=False,
        ).strip().lower()
        if ans not in ("", "y", "yes"):
            _print_summary(results, target_date, root_name, period, dry_run)
            return

    # --- Report ---
    report_filename = f"daily_internal_{target_date.strftime('%Y-%m-%d')}.md"

    def _upload_report():
        ctx.invoke(
            gdocs_upload_report,
            date_str=target_date.strftime("%Y%m%d"),
            dry_run=dry_run,
            force=force,
        )

    ok = _run_step("Report", report_filename, _upload_report)
    if not ok:
        ans = click.prompt(
            "Continue with remaining uploads? [Y/n]",
            default="Y",
            show_default=False,
        ).strip().lower()
        if ans not in ("", "y", "yes"):
            _print_summary(results, target_date, root_name, period, dry_run)
            return

    # --- Clockify ---
    clockify_filename = f"Clockify_{target_date.strftime('%Y%m%d')}.pdf"

    def _upload_clockify():
        ctx.invoke(
            gdocs_upload_clockify,
            date_str=target_date.strftime("%Y%m%d"),
            dry_run=dry_run,
            force=force,
        )

    _run_step("Clockify", clockify_filename, _upload_clockify)

    _print_summary(results, target_date, root_name, period, dry_run)


def _print_summary(
    results: dict, target_date: date, root_name: str, period: str, dry_run: bool
) -> None:
    """Print the upload summary table."""
    prefix = "[DRY RUN] " if dry_run else ""
    console.print(f"\n[bold]{prefix}Upload Summary — {target_date}[/bold]")
    labels = {
        "Notes":    (f"{root_name}/{period}/Raw_Notes/",  results.get("Notes")),
        "Report":   (f"{root_name}/{period}/Reports/",    results.get("Report")),
        "Clockify": (f"{root_name}/{period}/Clockify/",   results.get("Clockify")),
    }
    for label, (dest, result) in labels.items():
        if result is None:
            icon = "[yellow]–[/yellow]"
            detail = "skipped"
        elif result[0]:
            icon = "[green]✓[/green]"
            detail = f"→ {dest}{result[1]}"
        else:
            icon = "[red]✗[/red]"
            detail = result[1]
        console.print(f"  {icon} {label:<10} {detail}")
    console.print()
